import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'KUON CLASSICAL LAB — World\'s First Browser-Native music21 Environment | 空音開発',
  description:
    'World\'s first music education platform that runs real Python music21 inside the browser via Pyodide (Mozilla CPython on WebAssembly). Roman numeral analysis, voice leading checker, modulation map, MIDI playback for Bach, Mozart, Beethoven, Palestrina. Zero server cost, total privacy, offline-capable. Available from Prelude plan (¥780/mo).',
  keywords: [
    // Core technology
    'Pyodide music21',
    'WebAssembly music21',
    'browser Python music',
    'music21 in browser',
    'CPython WebAssembly',
    'Pyodide CPython',
    'music21 Pyodide',
    'in-browser music analysis',
    'serverless music analysis',
    'client-side Python music',
    // music21 specific
    'music21 MIT',
    'music21 Cuthbert',
    'music21 Roman numeral',
    'music21 Krumhansl-Schmuckler',
    'music21 cadence detection',
    'music21 voice leading',
    'music21 modulation analysis',
    'music21 chordify',
    'music21 corpus',
    'computational musicology',
    'music informatics',
    'MIR music information retrieval',
    // Educational
    'music theory in browser',
    'harmony homework checker',
    'voice leading checker',
    'parallel fifths detector',
    'parallel octaves detector',
    'cadence analyzer',
    'modulation analyzer',
    'Roman numeral analysis tool',
    'figured bass realization',
    'counterpoint analysis',
    'music school tool',
    'music conservatory tool',
    'Bach chorale analyzer',
    'Mozart sonata analyzer',
    'Beethoven quartet analyzer',
    'Palestrina mass analyzer',
    'Common Practice analysis',
    'Baroque harmony analysis',
    'Classical period harmony',
    'Romantic period harmony',
    // UX features
    'OpenSheetMusicDisplay OSMD',
    'Bravura SMuFL',
    'MIDI playback browser',
    'Tone.js music',
    'voice mute solo',
    'tempo control playback',
    'master volume control',
    'cursor follow score',
    'SATB analyzer',
    'four-voice harmony',
    // Privacy / cost
    'privacy-first music tool',
    'offline music analysis',
    'WiFi-cached music app',
    'zero-server music',
    'local-first music education',
    'unlimited music analysis',
    'no-quota music tool',
    'no-install music21',
    // KUON brand
    'KUON CLASSICAL LAB',
    'Kuon R&D',
    'Kuon Classical',
    '空音開発',
    'クラシカル ラボ',
    // ja
    'ブラウザ Python 音楽',
    'music21 ブラウザ',
    'WebAssembly 音楽分析',
    'Pyodide 音楽',
    '音楽情報学 ブラウザ',
    'ローマ数字分析 ブラウザ',
    '和声分析 ブラウザ',
    'バッハ コラール 分析',
    'モーツァルト 分析',
    'ベートーベン 分析',
    'パレストリーナ 分析',
    '声部進行 チェッカー',
    '連続五度 検出',
    '連続八度 検出',
    'カデンツ 検出',
    '転調 マップ',
    '芸大和声 ブラウザ',
    '音大生 ツール',
    'プライバシー 音楽',
    'オフライン 音楽分析',
    'サーバーレス 音楽',
    // de — German signups confirmed
    'music21 Browser',
    'Stufenanalyse Browser',
    'Stimmführungsprüfung',
    'Quintparallelen erkennen',
    'Oktavparallelen erkennen',
    'Bach Choral Analyse',
    'Mozart Quartett Analyse',
    'Harmonielehre Online',
    'Werkanalyse Browser',
    // es
    'análisis música navegador',
    'músicología computacional',
    'detector quintas paralelas',
    'análisis números romanos',
    // ko
    '브라우저 음악 분석',
    '음악정보학',
    '로마 숫자 분석',
    // pt
    'análise musical navegador',
    'algarismos romanos',
  ],
  openGraph: {
    title: 'KUON CLASSICAL LAB — Real music21 Running in Your Browser',
    description: 'World\'s first browser-native music21 environment via Pyodide. Zero server, total privacy, unlimited use. Bach, Mozart, Beethoven, Palestrina analysis instantly.',
    type: 'website',
    locale: 'ja_JP',
    alternateLocale: ['en_US', 'es_ES', 'ko_KR', 'pt_BR', 'de_DE'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'KUON CLASSICAL LAB',
    description: 'World\'s first browser-native music21 environment. Real Python, real analysis, zero server.',
  },
  alternates: {
    canonical: 'https://kuon-rnd.com/classical/lab-lp',
    languages: {
      ja: 'https://kuon-rnd.com/classical/lab-lp?lang=ja',
      en: 'https://kuon-rnd.com/classical/lab-lp?lang=en',
      es: 'https://kuon-rnd.com/classical/lab-lp?lang=es',
      ko: 'https://kuon-rnd.com/classical/lab-lp?lang=ko',
      pt: 'https://kuon-rnd.com/classical/lab-lp?lang=pt',
      de: 'https://kuon-rnd.com/classical/lab-lp?lang=de',
    },
  },
  robots: { index: true, follow: true },
};

export default function LabLPLayout({ children }: { children: React.ReactNode }) {
  return children;
}
