import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'KUON METRONOME — プロ音楽家監修メトロノーム + ジャズトレーニング LP | 空音開発',
  description:
    'プロの音楽家 朝比奈幸太郎 監修の世界最高ブラウザメトロノーム。サイレントバー練習・スピードトレーナー・ポリリズム・スウィング・変拍子グルーピング（5/8, 7/8, 11/8）・サブディビジョン（三連符〜七連符）・メトリックモジュレーション（♩=♩.・三連符・ダブルタイム・五連符・チェーン）・クラーベパターン（ソンクラーベ・ルンバ・ボサノバ・サンバ・ジャズライド・カスカラ）・ビートディスプレイスメント・オーバーザバーライン・チューニング基準音（A=440-443Hz）・プリセット・練習ログ。Web Audio API精密スケジューリング。音大受験・ジャズ練習・楽器練習に。ブラウザ完結・完全無料。',
  keywords: [
    'メトロノーム', 'metronome', 'オンラインメトロノーム', 'online metronome',
    'ブラウザメトロノーム', 'browser metronome', 'web metronome',
    'プロ監修メトロノーム', 'professional metronome', 'pro metronome',
    'タップテンポ', 'tap tempo', 'サイレントバー', 'silent bar practice',
    'silent bar metronome', 'internal pulse training',
    'スピードトレーナー', 'speed trainer', 'tempo trainer', 'auto tempo increase',
    'ポリリズム', 'polyrhythm', 'polyrhythm metronome', 'polyrhythm trainer',
    '2対3', '3対4', '4対5', '2 against 3', '3 against 4',
    'スウィング', 'swing', 'swing metronome', 'jazz swing',
    '変拍子', 'irregular meter', 'odd time signature', 'complex meter',
    '5/8', '7/8', '9/8', '11/8', '5/4', '7/4',
    'ビートグルーピング', 'beat grouping', '2+2+3', '3+2+2',
    'サブディビジョン', 'subdivision', '三連符', 'triplet', '五連符', 'quintuplet',
    'メトリックモジュレーション', 'metric modulation', 'metric modulation metronome',
    'metric modulation training', 'metric modulation practice',
    'tempo modulation', 'beat equivalence', 'tempo transition',
    '♩=♩.', 'dotted quarter modulation', 'triplet modulation', 'double time',
    'クラーベ', 'clave', 'clave metronome', 'clave practice',
    'ソンクラーベ', 'son clave 3-2', 'son clave 2-3', 'rumba clave',
    'ボサノバリズム', 'bossa nova rhythm', 'bossa nova metronome',
    'サンバリズム', 'samba rhythm', 'samba metronome',
    'ジャズライド', 'jazz ride pattern', 'spang-a-lang',
    'トレシージョ', 'tresillo', 'カスカラ', 'cascara',
    'ビートディスプレイスメント', 'beat displacement', 'rhythmic displacement',
    'displaced beat', 'displaced downbeat', 'jazz displacement training',
    'オーバーザバーライン', 'over the barline', 'over barline metronome',
    'cross-barline accent', 'polymetric accent', 'jazz phrasing training',
    '3 over 4', '5 over 4', '7 over 4', '4 over 3',
    'チューニング', 'tuning reference', 'A=442', 'A=440',
    'プリセット', 'preset', '練習ログ', 'practice log',
    'アクセントパターン', 'accent pattern', 'stress pattern',
    'BPM', 'tempo', '拍子', 'time signature',
    '音大受験', '楽器練習', 'music practice', 'instrument practice',
    'ジャズ練習', 'jazz practice', 'jazz training', 'jazz metronome',
    'ジャズメトロノーム', 'ラテンリズム', 'latin rhythm metronome',
    'ソルフェージュ', 'solfege', '朝比奈幸太郎',
    '메트로놈', '온라인 메트로놈', '탭 템포', '사일런트 바',
    '스피드 트레이너', '폴리리듬', '스윙', '변박자',
    '메트릭 모듈레이션', '클라베', '비트 디스플레이스먼트', '오버 더 바라인',
    '재즈 연습', '재즈 메트로놈', '음대 입시', '악기 연습',
    'metrónomo', 'metrónomo en línea', 'metrónomo online',
    'metrónomo profesional', 'metrónomo de jazz', 'polirritmia', 'compás irregular',
    'modulación métrica', 'clave', 'desplazamiento rítmico', 'sobre la barra',
    'entrenador de velocidad', 'práctica silenciosa', 'práctica de jazz',
    'metrônomo', 'metrônomo online', 'metrônomo profissional',
    'metrônomo de jazz', 'polirritmia', 'compasso irregular',
    'modulação métrica', 'clave', 'deslocamento rítmico', 'além da barra',
    'treinador de velocidade', 'prática de jazz',
  ],
  openGraph: {
    title: 'KUON METRONOME — Pro-Supervised Metronome + Jazz Training',
    description: 'Silent bar, speed trainer, polyrhythm, swing, metric modulation, clave patterns (Son, Rumba, Bossa Nova, Samba, Jazz Ride), beat displacement, over-the-barline. 13 pro features. Free.',
    url: 'https://kuon-rnd.com/metronome-lp',
    siteName: '空音開発 Kuon R&D',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'KUON METRONOME — Pro-Supervised + Jazz Training',
    description: 'Metric modulation, clave, beat displacement, over-the-barline, polyrhythm, swing. 13 pro features. Free browser metronome.',
  },
  alternates: {
    canonical: 'https://kuon-rnd.com/metronome-lp',
  },
};

export default function MetronomeLPLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
